[theme]
base = "dark"

primaryColor = "#4CAF50"  # a fresh green

backgroundColor = "#0E1117"   # main background
secondaryBackgroundColor = "#262730"  # sidebar/cards

textColor = "#FAFAFA"

font = "sans serif"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
toolbarMode = "minimal"
